model_params:
  model: ResnetUnet
  arch: resnet18
  pretrained: True
  num_classes: 1

args:
  expdir: segmentation

stages:

  state_params:
    num_epochs: 20
    main_metric: &reduce_metric iou_hard
    minimize_metric: False

  data_params:
    num_workers: 0
    batch_size: 8
    per_gpu_scaling: True
    image_size: 256
    in_csv_train: logs/datasets/Artelab/dataset_train.csv
    in_csv_valid: logs/datasets/Artelab/dataset_valid.csv
    datapath: logs/datasets/Artelab

  criterion_params:
    _key_value: True

    bce:
      criterion: BCEWithLogitsLoss
    dice:
      criterion: DiceLoss
    iou:
      criterion: IoULoss

  callbacks_params:
    loss_bce:
      callback: CriterionCallback
      input_key: mask
      output_key: logits
      prefix: loss
      criterion_key: bce
      multiplier: 1.0

    iou_soft:
      callback: IouCallback
      input_key: mask
      output_key: logits
      prefix: iou_soft
    iou_hard:
      callback: IouCallback
      input_key: mask
      output_key: logits
      prefix: iou_hard
      threshold: 0.5

    optimizer:
      callback: OptimizerCallback
      loss_key: loss
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  # train head
  stage1:

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

  # tune whole network
  stage2:

    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: SGD
      lr: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3
